# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
